# Generated by Django 4.2.1 on 2023-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employees_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='employee',
            field=models.ManyToManyField(to='employees.employees'),
        ),
    ]
