# Generated by Django 4.2.1 on 2023-05-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_tasks_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Describe',
        ),
    ]
