# Generated by Django 4.2.1 on 2023-05-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rename_departments_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('senioritylevel', models.CharField(max_length=30)),
                ('countofdepartment', models.IntegerField()),
                ('countofsubordinates', models.IntegerField()),
                ('descriptionofdepartment', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department'),
        ),
        migrations.DeleteModel(
            name='Describe',
        ),
    ]
