# Generated by Django 4.2.1 on 2023-05-19 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_department_alter_employees_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='pseudonym',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.pseudonym'),
        ),
    ]
