# Generated by Django 4.2.1 on 2023-05-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employees_pseudonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senioritylevel', models.CharField(max_length=30)),
                ('countofsubordinates', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='countofsubordinates',
        ),
        migrations.RemoveField(
            model_name='department',
            name='senioritylevel',
        ),
        migrations.AddField(
            model_name='employees',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.description'),
        ),
    ]
