# Generated by Django 4.2.1 on 2023-05-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_description_remove_department_countofsubordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='employee',
        ),
        migrations.AddField(
            model_name='employees',
            name='tasks',
            field=models.ManyToManyField(to='employees.tasks'),
        ),
    ]
